### ISSUE TITLE
Plain javascript examples please?

### ISSUE THREAD

**Issue by misterfresh** [9ballsyndrome/WebGL_Compute_shader#1]
Thank you for the interesting repo and demos, I'm looking forward to trying out compute shaders. However it would be nice to have some examples in plain Javascript. This would allow you to remove TypeScript conf files and also webpack, since you would not need to compile and could use native modules, making the whole repo much more simple and easy to read. 
Webgl is complicated enough so lets reduce the number of foreign concepts a newcomer has to grasp to get started, to showcase just what is possible to do in plain javascript (with the flags enabled obviously). In the current shape it is hard to read and see what is some typescript syntax, what is webgl, what is webpack stuff... It would be nice to just keep the webgl stuff, remove everything else, and keep it barebones. Great job otherwise!

**Comment by 9ballsyndrome** [comment]
@misterfresh 
Thank you for your suggestion! You are right. webpack, typescript or their config may be a bit confusing, and these are not the essence of this repository. I will work and update on this weekend.

**Comment by misterfresh** [comment]
@9ballsyndrome Awesome! As an exercise to try to understand the code, I adapted it a bit so that it runs with Chrome local files server. https://github.com/misterfresh/WebGL_Compute_shader . https://medium.com/@jmatix/using-chrome-as-a-local-web-server-af04baffd581

**Comment by 9ballsyndrome** [comment]
@misterfresh Great work! I didn't know Chrome local server thanks.
Then I rewrote the tutorial project using plain JavaScript.
Hope this helps newcomers understanding!

**Comment by misterfresh** [comment]
How did you learn to code this if I may ask? There is very little documentation on the web at the moment on that subject.

**Comment by 9ballsyndrome** [comment]
About compute shader itself?
Yes, there's almost no information using WebGL. But WebGL 2.0 Compute is a mirror of the OpenGL ES 3.1 feature set. So documentation and samples of OpenGL/ES compute shader on the web are useful(not so much info, though).
DirectX and Unity have compute shader too, so they will also help you.
Long ago, I had learned CUDA a little bit. This may be my basis of parallel computing.
And try and try...
