### ISSUE TITLE
Update documentation to list exact Chrome version required

### ISSUE THREAD

**Issue by temujin9** [9ballsyndrome/WebGL_Compute_shader#2]
The features that were in Canary three months ago may now be in dev. It would help (for those of us interested in testing) to know the exact version to look for.

**Comment by 9ballsyndrome** [comment]
@temujin9 
Thank you for your suggestion! I couldn't care about that. 
I tried again Canary, Dev, Beta, and also Stable and found all demos currently in this repository work in all of them.
I updated the documents.

**Comment by temujin9** [comment]
Fair enough. Thanks!
