### ISSUE TITLE
--use-angle=gl

### ISSUE THREAD

**Issue by pasu** [9ballsyndrome/WebGL_Compute_shader#3]
Hi, I installed the latest Canary version (74.0.3729.108), when I chose --use-angle=gl, the browser became black screen, Then, I tried to use D3D instead of gl, it works.

I guess the reason is my OS is Win10 and Win7, there is something wrong when ANGLE applied OpenGL.

Can you tell me the version of your OS. Based on the above reason, I guess it is not windows, I want to verify whether it is right.

I think maybe other people could meet the similar issue, so, they can try this way to avoid this situation.

**Comment by 9ballsyndrome** [comment]
@pasu 
Thank you for trying.
My primary environment is Windows 10 Pro 64 + NVIDIA GeForce GTX 1080 Ti

I've had probably the same issue(black screen when launched with gl) with my secondary environment: Windows 10 Pro 64 + Intel(R) UHD Graphics 620.
I solved the issue by updating the graphics driver to the latest.
So updating your graphics driver may help if it's not the latest.

If you are using Intel iGPU, you can check the driver in [here](https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html).

To check your GPU, visit chrome://gpu/ then it is listed in "GL_RENDERER" or "GPU0"

I hope this will help.

**Comment by pasu** [comment]
Thanks for your sharing.

The environment of my laptop is Win10 + (NVIDIA GeForce MX150 + Intel UHD Graphics 610), both the drivers of graphics cards are the latest.

The default setting of Chrome is integrated graphics (Intel), and the issue of black screen happens

When I switched 'GL_RENDERER' as MX150, and the issue of black screen is solved.
