### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ubernaut** [9ballsyndrome/WebGL_Compute_shader#4]
Thanks for the awesome demos. I've tested this on windows with chrome canary and it works like a charm. 

I saw you changed the text in your readme to state there is now Linux support so I installed the chrome dev channel release from here: https://www.chromium.org/getting-involved/dev-channel 

I was happy to see it listed in about:flags so I enabled it and gave it a shot:

![image](https://user-images.githubusercontent.com/1483522/57586861-78b58300-74a8-11e9-99be-0fc0188c5b38.png)

I'm running ubuntu 18.04 with an intel 620 integrated GPU. WebGL and shaders seem to work fine but your compute demos don't. 

I also tested this same laptop in windows with chrome canary and the demos did in fact work. 

I wonder if it's a driver issue.  Anyway, when I get home to my desktop I'll give it a shot with my linux box that has a Titan X GPU and see if it works there. 

thanks again for the bleeding edge work!

**Comment by ubernaut** [comment]
just wanted to add one more thing
![image](https://user-images.githubusercontent.com/1483522/57587011-c9c67680-74aa-11e9-8aeb-0f5d9ffdc52b.png)

the context is null, so it is probably an issue with the driver or the chrome dev channel. Sorry for bugging you.  I'm going to test it with my desktop later and post the results to this issue

**Comment by qjia7** [comment]
Did you add this flag `--use-gl=angle` for linux? On windows, it will use angle by default. However, on linux, you must specify it manually.
PS: The complete flags you need on linux: `--use-gl=angle  --use-angle=gl  --use-cmd-decoder=passthrough --enable-webgl2-compute-context`

**Comment by ubernaut** [comment]
@qjia7  w00t! thank you. now I can get back to work porting my physics stuff. 

THANK YOU!

**Comment by 9ballsyndrome** [comment]
@ubernaut 
Thank you for trying!
Sorry, actually I haven't tried this on Linux by myself yet. I added the description about Linux support to READMED in response to [Khronos's presentation](https://www.khronos.org/developers/library/2019-gdc): "WebGL Dev Day GDC Mar19" but I overlooked about the flag required for Linux. So your try whether my samples run fine on Linux is great help for me thanks!

**Comment by 9ballsyndrome** [comment]
@qjia7 
Thank you for your help!
The information is of great help for my understanding.
I had been wondering why this flag is remarked as required in some documents, but now it's cleared.
I added to the document about the command line flag required for Linux.
